name: Deploy on push master, main
on:
  push:
    branches: [ main, master ]
jobs:
  deploy:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          print("Hello")
          source(".github/scripts/deploy.R")
        shell: Rscript {0}
